export const GET_TASK_LOADING="GET_TASK_LOADING"
export const GET_TASK_SUCCESS="GET_TASK_SUCCESS"
export const GET_TASK_ERROR="GET_TASK_ERROR"

export const ADD_TASK_LOADING="ADD_TASK_LOADING"
export const ADD_TASK_SUCCESS="ADD_TASK_SUCCESS"
export const ADD_TASK_ERROR="ADD_TASK_ERROR"

export const PATCH_TASK_LOADING="PATCH_TASK_LOADING"
export const PATCH_TASK_SUCCESS="PATCH_TASK_SUCCESS"
export const PATCH_TASK_ERROR="PATCH_TASK_ERROR"

export const DELETE_TASK_LOADING="DELETE_TASK_LOADING"
export const DELETE_TASK_SUCCESS="DELETE_TASK_SUCCESS"
export const DELETE_TASK_ERROR="DELETE_TASK_ERROR"

